#ifdef WSAEINTR
case WSAEINTR: return "WSAEINTR";
#endif
#ifdef WSAEBADF
case WSAEBADF: return "WSAEBADF";
#endif
#ifdef WSAEACCES
case WSAEACCES: return "WSAEACCES";
#endif
#ifdef WSAEFAULT
case WSAEFAULT: return "WSAEFAULT";
#endif
#ifdef WSAEINVAL
case WSAEINVAL: return "WSAEINVAL";
#endif
#ifdef WSAEMFILE
case WSAEMFILE: return "WSAEMFILE";
#endif
#ifdef WSAEWOULDBLOCK
case WSAEWOULDBLOCK: return "WSAEWOULDBLOCK";
#endif
#ifdef WSAEINPROGRESS
case WSAEINPROGRESS: return "WSAEINPROGRESS";
#endif
#ifdef WSAEALREADY
case WSAEALREADY: return "WSAEALREADY";
#endif
#ifdef WSAENOTSOCK
case WSAENOTSOCK: return "WSAENOTSOCK";
#endif
#ifdef WSAEDESTADDRREQ
case WSAEDESTADDRREQ: return "WSAEDESTADDRREQ";
#endif
#ifdef WSAEMSGSIZE
case WSAEMSGSIZE: return "WSAEMSGSIZE";
#endif
#ifdef WSAEPROTOTYPE
case WSAEPROTOTYPE: return "WSAEPROTOTYPE";
#endif
#ifdef WSAENOPROTOOPT
case WSAENOPROTOOPT: return "WSAENOPROTOOPT";
#endif
#ifdef WSAEPROTONOSUPPORT
case WSAEPROTONOSUPPORT: return "WSAEPROTONOSUPPORT";
#endif
#ifdef WSAESOCKTNOSUPPORT
case WSAESOCKTNOSUPPORT: return "WSAESOCKTNOSUPPORT";
#endif
#ifdef WSAEOPNOTSUPP
case WSAEOPNOTSUPP: return "WSAEOPNOTSUPP";
#endif
#ifdef WSAEPFNOSUPPORT
case WSAEPFNOSUPPORT: return "WSAEPFNOSUPPORT";
#endif
#ifdef WSAEAFNOSUPPORT
case WSAEAFNOSUPPORT: return "WSAEAFNOSUPPORT";
#endif
#ifdef WSAEADDRINUSE
case WSAEADDRINUSE: return "WSAEADDRINUSE";
#endif
#ifdef WSAEADDRNOTAVAIL
case WSAEADDRNOTAVAIL: return "WSAEADDRNOTAVAIL";
#endif
#ifdef WSAENETDOWN
case WSAENETDOWN: return "WSAENETDOWN";
#endif
#ifdef WSAENETUNREACH
case WSAENETUNREACH: return "WSAENETUNREACH";
#endif
#ifdef WSAENETRESET
case WSAENETRESET: return "WSAENETRESET";
#endif
#ifdef WSAECONNABORTED
case WSAECONNABORTED: return "WSAECONNABORTED";
#endif
#ifdef WSAECONNRESET
case WSAECONNRESET: return "WSAECONNRESET";
#endif
#ifdef WSAENOBUFS
case WSAENOBUFS: return "WSAENOBUFS";
#endif
#ifdef WSAEISCONN
case WSAEISCONN: return "WSAEISCONN";
#endif
#ifdef WSAENOTCONN
case WSAENOTCONN: return "WSAENOTCONN";
#endif
#ifdef WSAESHUTDOWN
case WSAESHUTDOWN: return "WSAESHUTDOWN";
#endif
#ifdef WSAETOOMANYREFS
case WSAETOOMANYREFS: return "WSAETOOMANYREFS";
#endif
#ifdef WSAETIMEDOUT
case WSAETIMEDOUT: return "WSAETIMEDOUT";
#endif
#ifdef WSAECONNREFUSED
case WSAECONNREFUSED: return "WSAECONNREFUSED";
#endif
#ifdef WSAELOOP
case WSAELOOP: return "WSAELOOP";
#endif
#ifdef WSAENAMETOOLONG
case WSAENAMETOOLONG: return "WSAENAMETOOLONG";
#endif
#ifdef WSAEHOSTDOWN
case WSAEHOSTDOWN: return "WSAEHOSTDOWN";
#endif
#ifdef WSAEHOSTUNREACH
case WSAEHOSTUNREACH: return "WSAEHOSTUNREACH";
#endif
#ifdef WSAENOTEMPTY
case WSAENOTEMPTY: return "WSAENOTEMPTY";
#endif
#ifdef WSAEPROCLIM
case WSAEPROCLIM: return "WSAEPROCLIM";
#endif
#ifdef WSAEUSERS
case WSAEUSERS: return "WSAEUSERS";
#endif
#ifdef WSAEDQUOT
case WSAEDQUOT: return "WSAEDQUOT";
#endif
#ifdef WSAESTALE
case WSAESTALE: return "WSAESTALE";
#endif
#ifdef WSAEREMOTE
case WSAEREMOTE: return "WSAEREMOTE";
#endif
#ifdef WSASYSNOTREADY
case WSASYSNOTREADY: return "WSASYSNOTREADY";
#endif
#ifdef WSAVERNOTSUPPORTED
case WSAVERNOTSUPPORTED: return "WSAVERNOTSUPPORTED";
#endif
#ifdef WSANOTINITIALISED
case WSANOTINITIALISED: return "WSANOTINITIALISED";
#endif
#ifdef WSAEDISCON
case WSAEDISCON: return "WSAEDISCON";
#endif
#ifdef WSAENOMORE
case WSAENOMORE: return "WSAENOMORE";
#endif
#ifdef WSAECANCELLED
case WSAECANCELLED: return "WSAECANCELLED";
#endif
#ifdef WSAEINVALIDPROCTABLE
case WSAEINVALIDPROCTABLE: return "WSAEINVALIDPROCTABLE";
#endif
#ifdef WSAEINVALIDPROVIDER
case WSAEINVALIDPROVIDER: return "WSAEINVALIDPROVIDER";
#endif
#ifdef WSAEPROVIDERFAILEDINIT
case WSAEPROVIDERFAILEDINIT: return "WSAEPROVIDERFAILEDINIT";
#endif
#ifdef WSASYSCALLFAILURE
case WSASYSCALLFAILURE: return "WSASYSCALLFAILURE";
#endif
#ifdef WSASERVICE_NOT_FOUND
case WSASERVICE_NOT_FOUND: return "WSASERVICE_NOT_FOUND";
#endif
#ifdef WSATYPE_NOT_FOUND
case WSATYPE_NOT_FOUND: return "WSATYPE_NOT_FOUND";
#endif
#ifdef WSA_E_NO_MORE
case WSA_E_NO_MORE: return "WSA_E_NO_MORE";
#endif
#ifdef WSA_E_CANCELLED
case WSA_E_CANCELLED: return "WSA_E_CANCELLED";
#endif
#ifdef WSAEREFUSED
case WSAEREFUSED: return "WSAEREFUSED";
#endif
#ifdef WSAHOST_NOT_FOUND
case WSAHOST_NOT_FOUND: return "WSAHOST_NOT_FOUND";
#endif
#ifdef WSATRY_AGAIN
case WSATRY_AGAIN: return "WSATRY_AGAIN";
#endif
#ifdef WSANO_RECOVERY
case WSANO_RECOVERY: return "WSANO_RECOVERY";
#endif
#ifdef WSANO_DATA
case WSANO_DATA: return "WSANO_DATA";
#endif
#ifdef WSA_QOS_RECEIVERS
case WSA_QOS_RECEIVERS: return "WSA_QOS_RECEIVERS";
#endif
#ifdef WSA_QOS_SENDERS
case WSA_QOS_SENDERS: return "WSA_QOS_SENDERS";
#endif
#ifdef WSA_QOS_NO_SENDERS
case WSA_QOS_NO_SENDERS: return "WSA_QOS_NO_SENDERS";
#endif
#ifdef WSA_QOS_NO_RECEIVERS
case WSA_QOS_NO_RECEIVERS: return "WSA_QOS_NO_RECEIVERS";
#endif
#ifdef WSA_QOS_REQUEST_CONFIRMED
case WSA_QOS_REQUEST_CONFIRMED: return "WSA_QOS_REQUEST_CONFIRMED";
#endif
#ifdef WSA_QOS_ADMISSION_FAILURE
case WSA_QOS_ADMISSION_FAILURE: return "WSA_QOS_ADMISSION_FAILURE";
#endif
#ifdef WSA_QOS_POLICY_FAILURE
case WSA_QOS_POLICY_FAILURE: return "WSA_QOS_POLICY_FAILURE";
#endif
#ifdef WSA_QOS_BAD_STYLE
case WSA_QOS_BAD_STYLE: return "WSA_QOS_BAD_STYLE";
#endif
#ifdef WSA_QOS_BAD_OBJECT
case WSA_QOS_BAD_OBJECT: return "WSA_QOS_BAD_OBJECT";
#endif
#ifdef WSA_QOS_TRAFFIC_CTRL_ERROR
case WSA_QOS_TRAFFIC_CTRL_ERROR: return "WSA_QOS_TRAFFIC_CTRL_ERROR";
#endif
#ifdef WSA_QOS_GENERIC_ERROR
case WSA_QOS_GENERIC_ERROR: return "WSA_QOS_GENERIC_ERROR";
#endif
#ifdef WSA_QOS_ESERVICETYPE
case WSA_QOS_ESERVICETYPE: return "WSA_QOS_ESERVICETYPE";
#endif
#ifdef WSA_QOS_EFLOWSPEC
case WSA_QOS_EFLOWSPEC: return "WSA_QOS_EFLOWSPEC";
#endif
#ifdef WSA_QOS_EPROVSPECBUF
case WSA_QOS_EPROVSPECBUF: return "WSA_QOS_EPROVSPECBUF";
#endif
#ifdef WSA_QOS_EFILTERSTYLE
case WSA_QOS_EFILTERSTYLE: return "WSA_QOS_EFILTERSTYLE";
#endif
#ifdef WSA_QOS_EFILTERTYPE
case WSA_QOS_EFILTERTYPE: return "WSA_QOS_EFILTERTYPE";
#endif
#ifdef WSA_QOS_EFILTERCOUNT
case WSA_QOS_EFILTERCOUNT: return "WSA_QOS_EFILTERCOUNT";
#endif
#ifdef WSA_QOS_EOBJLENGTH
case WSA_QOS_EOBJLENGTH: return "WSA_QOS_EOBJLENGTH";
#endif
#ifdef WSA_QOS_EFLOWCOUNT
case WSA_QOS_EFLOWCOUNT: return "WSA_QOS_EFLOWCOUNT";
#endif
#ifdef WSA_QOS_EUNKNOWNPSOBJ
case WSA_QOS_EUNKNOWNPSOBJ: return "WSA_QOS_EUNKNOWNPSOBJ";
#endif
#ifdef WSA_QOS_EPOLICYOBJ
case WSA_QOS_EPOLICYOBJ: return "WSA_QOS_EPOLICYOBJ";
#endif
#ifdef WSA_QOS_EFLOWDESC
case WSA_QOS_EFLOWDESC: return "WSA_QOS_EFLOWDESC";
#endif
#ifdef WSA_QOS_EPSFLOWSPEC
case WSA_QOS_EPSFLOWSPEC: return "WSA_QOS_EPSFLOWSPEC";
#endif
#ifdef WSA_QOS_EPSFILTERSPEC
case WSA_QOS_EPSFILTERSPEC: return "WSA_QOS_EPSFILTERSPEC";
#endif
#ifdef WSA_QOS_ESDMODEOBJ
case WSA_QOS_ESDMODEOBJ: return "WSA_QOS_ESDMODEOBJ";
#endif
#ifdef WSA_QOS_ESHAPERATEOBJ
case WSA_QOS_ESHAPERATEOBJ: return "WSA_QOS_ESHAPERATEOBJ";
#endif
#ifdef WSA_QOS_RESERVED_PETYPE
case WSA_QOS_RESERVED_PETYPE: return "WSA_QOS_RESERVED_PETYPE";
#endif
